Repository codeit-bootcamp-spring/3-sprint-mission, pull requests merged in 2025-08, with the labels that each got.

#244 [한동우] sprint9
  .gitignore
  build.gradle
  src/main/java/com/sprint/mission/discodeit/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/sprint/mission/discodeit/auth/handler/CustomSessionExpiredStrategy.java
  src/main/java/com/sprint/mission/discodeit/auth/handler/LoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/auth/handler/LoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/auth/service/DiscodeitUserDetails.java
  src/main/java/com/sprint/mission/discodeit/auth/service/DiscodeitUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/auth/LoginDto.java
  src/main/java/com/sprint/mission/discodeit/dto/auth/RoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/user/UserResponseDto.java
  src/main/java/com/sprint/mission/discodeit/dto/userstatus/UserStatusRequestDto.java
  src/main/java/com/sprint/mission/discodeit/dto/userstatus/UserStatusResponseDto.java
  src/main/java/com/sprint/mission/discodeit/dto/userstatus/UserStatusUpdateDto.java
  src/main/java/com/sprint/mission/discodeit/entity/Role.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/NotFoundUserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusAlreadyExistsException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusException.java
  src/main/java/com/sprint/mission/discodeit/init/AdminInitializer.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserStatusMapper.java
  src/main/java/com/sprint/mission/discodeit/mapper/struct/UserStatusStructMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/security/MessageSecurity.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/java/com/sprint/mission/discodeit/storage/s3/S3BinaryContentStorage.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CpA9o6ho.js
  src/main/resources/static/assets/index-DRjprt8D.js
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/ChannelServiceIntegrationTest.java
  src/test/java/com/sprint/mission/discodeit/MessageServiceIntegrationTest.java
  src/test/java/com/sprint/mission/discodeit/UserServiceIntegrationTest.java
  src/test/java/com/sprint/mission/discodeit/controller/AuthControllerTest.java
  src/test/java/com/sprint/mission/discodeit/controller/ChannelControllerTest.java
  src/test/java/com/sprint/mission/discodeit/controller/MessageControllerTest.java
  src/test/java/com/sprint/mission/discodeit/controller/UserControllerTest.java
  src/test/java/com/sprint/mission/discodeit/repository/MessageRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/repository/UserRepositoryTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceTest.java
Labels: 매운맛🔥

#278 [박진솔] sprint10
  3-sprint-mission/build.gradle
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/config/AppConfig.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/dto/data/JwtDto.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/dto/data/JwtInformation.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/dto/request/LoginRequest.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/dto/response/ErrorResponse.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/exception/ErrorCode.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/handler/Http403ForbiddenAccessDeniedHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/handler/HttpStatusReturningLogoutSuccessHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/handler/JwtLoginSuccessHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/handler/JwtLogoutHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/handler/LoginFailureHandler.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/security/AdminInitializer.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/security/jwt/InMemoryJwtRegistry.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/security/jwt/JwtAuthenticationFilter.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/security/jwt/JwtRegistry.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/security/jwt/JwtTokenProvider.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  3-sprint-mission/src/main/resources/application-dev.yaml
  3-sprint-mission/src/main/resources/application.yaml
  3-sprint-mission/src/main/resources/schema.sql
  3-sprint-mission/src/main/resources/static/assets/index-COLcXNzv.js
  3-sprint-mission/src/test/java/com/sprint/mission/discodeit/controller/ChannelControllerTest.java
  3-sprint-mission/src/test/java/com/sprint/mission/discodeit/controller/MessageControllerTest.java
  3-sprint-mission/src/test/java/com/sprint/mission/discodeit/integration/AuthApiIntegrationTest.java
  3-sprint-mission/src/test/java/com/sprint/mission/discodeit/service/basic/BasicMessageServiceTest.java
  3-sprint-mission/src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceTest.java
  3-sprint-mission/src/test/resources/application-test.yaml
Labels: 순한맛🐑, 지각제출⏰

#256 [임정현] sprint9
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  .gitignore
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/AdminInitializer.java
  src/main/java/com/sprint/mission/discodeit/config/MDCLoggingFilter.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserStatusDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/LoginRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/user/RoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/userStatus/UserStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/userStatus/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/Role.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/ErrorCode.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/DuplicatedUserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusException.java
  src/main/java/com/sprint/mission/discodeit/exception/userstatus/UserStatusNotFoundException.java
  src/main/java/com/sprint/mission/discodeit/handler/CustomAccessDeniedHandler.java
  src/main/java/com/sprint/mission/discodeit/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/sprint/mission/discodeit/handler/LoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/handler/LoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserStatusMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/DiscodeitUserDetails.java
  src/main/java/com/sprint/mission/discodeit/service/DiscodeitUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-CpA9o6ho.js
  src/main/resources/static/assets/index-D8OMG6Bz.js
  src/main/resources/static/error.html
  src/main/resources/static/index.html
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 매운맛🔥

#274 조현아 sprint10
  README.md
  build.gradle
  src/main/java/com/sprint/mission/discodeit/config/AppConfig.java
  src/main/java/com/sprint/mission/discodeit/config/MethodSecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/config/QueryDslConfig.java
  src/main/java/com/sprint/mission/discodeit/config/RoleHierarchyConfig.java
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/config/SwaggerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/JwtDto.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/RoleUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/mapper/UserMapper.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageCustomRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageCustomRepositoryImpl.java
  src/main/java/com/sprint/mission/discodeit/security/DiscodeitUserDetails.java
  src/main/java/com/sprint/mission/discodeit/security/DiscodeitUserDetailsService.java
  src/main/java/com/sprint/mission/discodeit/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/sprint/mission/discodeit/security/handler/CustomSessionExpiredStrategy.java
  src/main/java/com/sprint/mission/discodeit/security/handler/LoginFailureHandler.java
  src/main/java/com/sprint/mission/discodeit/security/handler/LoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/initializer/AdminInitializer.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtInformation.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtTokenProvider.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/handler/JwtLoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/handler/JwtLogoutHandler.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/store/InMemoryJwtRegistry.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/store/JwtRegistry.java
  src/main/java/com/sprint/mission/discodeit/security/permission/UserPermissionEvaluator.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserSessionService.java
  src/main/resources/application.yaml
  src/main/resources/fe_bundle_1.2.3.zip
  src/main/resources/schema.sql
  src/main/resources/static/assets/index-COLcXNzv.js
  src/main/resources/static/assets/index-CpA9o6ho.js
  src/main/resources/static/index.html
  src/test/java/com/sprint/mission/discodeit/config/TestQuerydslConfig.java
  src/test/java/com/sprint/mission/discodeit/controller/MessageControllerTest.java
  src/test/java/com/sprint/mission/discodeit/controller/UserControllerTest.java
  src/test/java/com/sprint/mission/discodeit/integration/UserIntegrationTest.java
  src/test/java/com/sprint/mission/discodeit/service/basic/BasicUserServiceTest.java
  src/test/java/com/sprint/mission/discodeit/storage/s3/AWSS3Test.java
Labels: 순한맛🐑

#280 [김민준] sprint10
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/config/SecurityConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/BinaryContentApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ChannelApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ReadStatusApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/dto/data/JwtDto.java
  src/main/java/com/sprint/mission/discodeit/dto/data/JwtInformation.java
  src/main/java/com/sprint/mission/discodeit/security/Http403ForbiddenAccessDeniedHandler.java
  src/main/java/com/sprint/mission/discodeit/security/SessionManager.java
  src/main/java/com/sprint/mission/discodeit/security/SpaCsrfTokenRequestHandler.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtLoginSuccessHandler.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtLogoutHandler.java
  src/main/java/com/sprint/mission/discodeit/security/jwt/JwtTokenProvider.java
Labels: 매운맛🔥, 미완성🛠️, 지각제출⏰
