Repository codeit-bootcamp-spring/3-sprint-mission, pull requests merged in 2025-05, with the labels that each got.

#53 [고희준] sprint2
  src/main/java/com/sprint/JavaApplication.java
  src/main/java/com/sprint/JavaApplication2.java
  src/main/java/com/sprint/JavaApplication3.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/menu/ChannelMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/MessageMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/UserMenu.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/DefaultChannelFactory.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#86 [이승진] sprint3
  .gitattributes
  .gitignore
  build.gradle
  data/channels/046651cd-e3d6-40fc-ab14-4d47b1fc77d3.ser
  data/channels/22beb428-9f2a-48e9-a09e-d1d2b5bad23a.ser
  data/channels/34cca23e-5538-479f-8a24-a82aca9f193c.ser
  data/channels/70144502-341c-4170-838d-58f8544b682f.ser
  data/channels/7e25eecb-a0e9-4d00-a7ef-54c13069b030.ser
  data/channels/8c657a6b-5aa8-4884-a978-d77bd5cc561c.ser
  data/channels/917868b4-f9c1-4af9-999d-ee4b59db1b10.ser
  data/channels/99761b2a-6df9-4cd6-a0a4-b8fdbb828efe.ser
  data/channels/afad5d30-50fa-446a-8d9a-fcab25e497fd.ser
  data/channels/b524398a-ddfd-4b50-9a7e-c50a163912f4.ser
  data/channels/b751691d-17c4-494e-9063-554cb23b59fd.ser
  data/channels/c0ec3b9b-f9eb-45e5-86ae-51afbb709cc0.ser
  data/channels/e03bace5-5392-4465-bba7-35f69f3ce4b1.ser
  data/channels/e2fdb1f3-7249-471c-b89d-c1623a5081eb.ser
  data/channels/feebd48c-4b76-4424-bb5c-f25e4e435a88.ser
  data/messages/12db7722-5404-46e4-b987-782c61f6a0a8.ser
  data/messages/88484a78-4d37-4f2a-9a04-c854acc9877f.ser
  data/messages/c21f582e-b1e1-430f-82c9-7cb002fc7971.ser
  data/users/263f5c80-83aa-4788-80fa-44fde778e95f.ser
  data/users/3eda3cd0-2e94-4048-9823-2fbdebcff6fa.ser
  data/users/4462de19-1494-40a0-b52a-e118dffe7108.ser
  data/users/47c83edb-5d15-4215-a4ae-5f8fbf165e43.ser
  data/users/50961450-85c0-46b6-87d1-d7ff298e5c98.ser
  data/users/5c2eec97-e698-4eb6-bbcd-ac33159e7cff.ser
  data/users/70c775f7-5829-4931-9b86-fc098d7ef600.ser
  data/users/da25d671-208d-4d9a-8667-c21a8a4e2ed7.ser
  data/users/db6fe9ea-4ae1-43c6-8b91-364c4c96f216.ser
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/application.properties
  src/test/java/com/sprint/mission/discodeit/DiscodeitApplicationTests.java
Labels: 매운맛🔥, 미완성🛠️

#88 이채원
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥, 미완성🛠️

#84 [황지인] sprint3
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ChannelUpdateNameRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/LoginRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/PrivateChannelRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ProfileImageCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/PublicChannelRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ReadStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/ReadStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserProfileImageUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserStatusCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/response/ChannelFindResponse.java
  src/main/java/com/sprint/mission/discodeit/dto/response/UserCreateResponse.java
  src/main/java/com/sprint/mission/discodeit/dto/response/UserResponse.java
  src/main/java/com/sprint/mission/discodeit/dto/response/UserStatusCreateResponse.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/repository/BinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
Labels: 미완성🛠️

#29 [이주용] sprint1
  .gitignore
  .idea/.gitignore
  .idea/gradle.xml
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/vcs.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/factory/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/resources/log4j2.xml
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFChannelServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFMessageServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFUserServiceTest.java
Labels: 매운맛🔥

#95 [강문구] sprint4
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/CreateBinaryContentRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/CreateMessageRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/FindUserRespond.java
  src/main/java/com/sprint/mission/discodeit/dto/UpdateMessageRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/UpdateUserRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/UserDto.java
  src/main/java/com/sprint/mission/discodeit/entitiy/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entitiy/User.java
  src/main/java/com/sprint/mission/discodeit/entitiy/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/data/binarycontent.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/channel.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/message.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/readstatus.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/user.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/userstatus.ser
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/BinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
  src/main/resources/static/default-avatar.png
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 매운맛🔥

#112 [김현기] sprint4
  discodeit/src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/binarycontent/AddBinaryContentRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/binarycontent/CreateBinaryContentRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/channel/CreatePrivateChannelRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/channel/PrivateChannelDTO.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/channel/PublicChannelDTO.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/channel/UpdateChannelRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/message/MessageDTO.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/message/UpdateMessageRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/user/LoginRequest.java
  discodeit/src/main/java/com/sprint/mission/discodeit/dto/user/UserDTO.java
  discodeit/src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  discodeit/src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  discodeit/src/main/java/com/sprint/mission/discodeit/entity/Message.java
  discodeit/src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  discodeit/src/main/java/com/sprint/mission/discodeit/entity/User.java
  discodeit/src/main/java/com/sprint/mission/discodeit/factory/BasicServiceFactory.java
  discodeit/src/main/java/com/sprint/mission/discodeit/files/channels.json
  discodeit/src/main/java/com/sprint/mission/discodeit/files/messages.json
  discodeit/src/main/java/com/sprint/mission/discodeit/files/users.json
  discodeit/src/main/java/com/sprint/mission/discodeit/files/userstatus.json
  discodeit/src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  discodeit/src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  discodeit/src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFReadStatusRepository.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/ReaduStatusService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/UserService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  discodeit/src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  discodeit/src/main/resources/application.yaml
  discodeit/src/main/resources/static/script.js
  discodeit/src/main/resources/static/styles.css
  discodeit/src/main/resources/static/user-list.html
Labels: 순한맛🐑

#124 [강우진] sprint4
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/data/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/request/BinaryContentCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/request/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/AbstractFileRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/ReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfReadStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JcfUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 매운맛🔥, 미완성🛠️

#114 [강문구] sprint4
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/CreateBinaryContentRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/CreateMessageRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/FindUserRespond.java
  src/main/java/com/sprint/mission/discodeit/dto/UpdateMessageRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/UpdateUserRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/UserDto.java
  src/main/java/com/sprint/mission/discodeit/entitiy/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entitiy/User.java
  src/main/java/com/sprint/mission/discodeit/entitiy/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/data/binarycontent.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/channel.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/message.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/readstatus.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/user.ser
  src/main/java/com/sprint/mission/discodeit/repository/file/data/userstatus.ser
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFBinaryContentRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/BinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
  src/main/resources/static/default-avatar.png
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
Labels: 매운맛🔥

#94 [이지현] sprint4
  .discodeit/Channel/29a5cedd-e954-4302-a14e-1e35388be62a.ser
  .discodeit/Message/ae7c5d56-f5b0-419d-822d-71504714aab3.ser
  .discodeit/User/02c25b6b-1f84-408b-b7dd-141bc079e560.ser
  .discodeit/UserStatus/ca72094c-b22a-457b-b213-8ec04217332a.ser
  .gitignore
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/controller/MainController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/BinaryContent/BinaryContentCreateRequestDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/ChannelDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/PrivateChannelCreateRequestDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/ReadStatus/ReadStatusCreateRequestDTO.java
  src/main/java/com/sprint/mission/discodeit/dto/User/UserDTO.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/ChannelType.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/ReadStatus.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/entity/UserStatus.java
  src/main/java/com/sprint/mission/discodeit/service/BinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserStatusService.java
  src/main/resources/application.yaml
  src/main/resources/static/default-avatar.png
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list-by-ai.html
  src/main/resources/static/user-list.html
Labels: 매운맛🔥

#150 [고희준] sprint5
  .discodeit/Channel/239eef81-4159-4aa5-b4a6-396152b59822.ser
  .discodeit/Message/0d0b1104-3735-4d26-b25d-368954c1c9b9.ser
  .discodeit/Message/fa962b5f-34e6-4e97-ab60-adedccf0ab5d.ser
  .discodeit/ReadStatus/e326ff4b-3ebe-49fa-90ac-a4e69f91c1f4.ser
  .discodeit/User/d125859c-9301-468d-8f45-b9e1afdc24b9.ser
  .discodeit/UserStatus/d125859c-9301-468d-8f45-b9e1afdc24b9.ser
  .gitignore
  build.gradle
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/dto/AuthLogin/LoginRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/BinaryContent/BinaryContentCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/ChannelDto.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/ChannelUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/PrivateChannelCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/Channel/PublicChannelCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/Message/MessageUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/User/UserCreateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/User/UserDto.java
  src/main/java/com/sprint/mission/discodeit/dto/User/UserUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/dto/UserStatus/UserStatusUpdateRequest.java
  src/main/java/com/sprint/mission/discodeit/entity/BinaryContent.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/exception/ErrorResponse.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/service/AuthService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/ReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/UserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BaiscUserStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicAuthService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicBinaryContentService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicReadStatusService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/resources/application.yaml
  src/main/resources/static/assets/index-CRrRqFH4.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/index.html
Labels: 매운맛🔥

#148 [정윤지] sprint5
  build.gradle
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/exception/GlobalExceptionHandler.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserStatusRepository.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
Labels: 매운맛🔥

#161 [김민준] sprint5
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/sprint/mission/discodeit/DiscodeitApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/MainApplication.java
  src/main/java/com/sprint/mission/discodeit/config/RepositoryConfig.java
  src/main/java/com/sprint/mission/discodeit/config/ServiceConfig.java
  src/main/java/com/sprint/mission/discodeit/config/SwaggerConfig.java
  src/main/java/com/sprint/mission/discodeit/controller/AuthController.java
  src/main/java/com/sprint/mission/discodeit/controller/BinaryContentController.java
  src/main/java/com/sprint/mission/discodeit/controller/ChannelController.java
  src/main/java/com/sprint/mission/discodeit/controller/MessageController.java
  src/main/java/com/sprint/mission/discodeit/controller/ReadStatusController.java
  src/main/java/com/sprint/mission/discodeit/controller/UserController.java
  src/main/java/com/sprint/mission/discodeit/controller/api/AuthApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/BinaryContentApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ChannelApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/MessageApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/ReadStatusApi.java
  src/main/java/com/sprint/mission/discodeit/controller/api/UserApi.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/impl/BinaryContentServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/impl/ChannelServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/impl/MessageServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/impl/ReadStatusServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/impl/UserServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/impl/UserStatusServiceImpl.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/test/TestChannel.java
  src/main/java/com/sprint/mission/discodeit/test/TestMessage.java
  src/main/java/com/sprint/mission/discodeit/test/TestUser.java
  src/main/resources/.DS_Store
  src/main/resources/Application.yaml
  src/main/resources/application.yaml
  src/main/resources/static/.DS_Store
  src/main/resources/static/assets/index-CRrRqFH4.js
  src/main/resources/static/assets/index-kQJbKSsj.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fe_1.0.0/.DS_Store
  src/main/resources/static/index.html
  src/main/resources/static/script.js
  src/main/resources/static/styles.css
  src/main/resources/static/user-list.html
  src/test/java/test/com/sprint/mission/discodeit/DiscodeitApplicationTests.java
Labels: 매운맛🔥, 지각제출⏰
