Repository codeit-bootcamp-spring/3-sprint-mission, pull requests merged in 2025-04, with the labels that each got.

#22 [정윤지] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Common.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#23 [이승진] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
Labels: 매운맛🔥

#13 [김유빈] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥, 순한맛🐑

#34 [이채원] Sprint1
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/Main.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 순한맛🐑

#32 [김민준] Sprint1
  .gitattributes
  .gitignore
  app/build.gradle
  app/src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  app/src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  app/src/main/java/com/sprint/mission/discodeit/entity/Message.java
  app/src/main/java/com/sprint/mission/discodeit/entity/User.java
  app/src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  app/src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  app/src/main/java/com/sprint/mission/discodeit/service/UserService.java
  app/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  app/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  app/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  app/src/main/java/com/sprint/mission/discodeit/test/TestChannel.java
  app/src/main/java/com/sprint/mission/discodeit/test/TestMessage.java
  app/src/main/java/com/sprint/mission/discodeit/test/TestUser.java
  app/src/test/java/org/example/AppTest.java
  gradle.properties
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 매운맛🔥

#18 [조재구] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/_test_/TestChannel.java
  src/main/java/com/sprint/mission/discodeit/_test_/TestCommon.java
  src/main/java/com/sprint/mission/discodeit/_test_/TestMessage.java
  src/main/java/com/sprint/mission/discodeit/_test_/TestUser.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Common.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#11 [김동욱] sprint1
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#39 [이채원] sprint1
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#28 [백은호] Sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/run/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFChannelServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFMessageServiceTest.java
  src/test/java/com/sprint/mission/discodeit/service/jcf/JCFUserServiceTest.java
Labels: 매운맛🔥

#1 [강문구] sprint1
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entitiy/Channel.java
  src/main/java/com/sprint/mission/discodeit/entitiy/Message.java
  src/main/java/com/sprint/mission/discodeit/entitiy/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥, 순한맛🐑

#2 [안여경] sprint1
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#14 [이건민] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 순한맛🐑

#26 [임정현] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Base.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  f
Labels: 매운맛🔥, 미완성🛠️

#31 [황지인] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/Factory/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/run/Application.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#25 [강우진] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/factory/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JcfChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JcfMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JcfUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JcfUserServiceUsingMap.java
Labels: 매운맛🔥

#27 [조현아] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/factory/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 순한맛🐑

#19 [고희준] sprint1
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/menu/ChannelMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/MessageMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/UserMenu.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#21 [이지현] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/entity/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/menu/ChannelMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/ChatMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/UserMenu.java
  src/main/java/com/sprint/mission/discodeit/run/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#33 [조백선] sprint1
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/menu/ChannelMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/MessageMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/UserMenu.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#35 [박진솔] sprint1
  3-sprint-mission/.gitignore
  3-sprint-mission/build.gradle
  3-sprint-mission/gradle/wrapper/gradle-wrapper.jar
  3-sprint-mission/gradle/wrapper/gradle-wrapper.properties
  3-sprint-mission/gradlew
  3-sprint-mission/gradlew.bat
  3-sprint-mission/settings.gradle
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/Message.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/User.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/run/JavaApplication.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/UserService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  3-sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 미완성🛠️, 순한맛🐑

#64 [김민준] sprint2
  .gitignore
  app/build.gradle
  app/src/main/java/com/sprint/mission/discodeit/entity/User.java
  app/src/test/java/org/example/AppTest.java
  settings.gradle
  src/build.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication2.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/test/TestChannel.java
  src/main/java/com/sprint/mission/discodeit/test/TestMessage.java
  src/main/java/com/sprint/mission/discodeit/test/TestUser.java
Labels: 매운맛🔥, 지각제출⏰

#57 [김유빈] sprint2
  build.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication2.java
  src/main/java/com/sprint/mission/discodeit/Repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/Repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#65 [이채원] sprint2
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥, 지각제출⏰

#56 [이승진] sprin2
  build.gradle
  data/channels/05196f3c-598e-4f0e-9e1b-dfdbf3015722.ser
  data/channels/1771a58a-94b5-4e6b-b1c1-f547dba044ff.ser
  data/channels/3e67cb93-b691-4cae-8509-5195f53e42d0.ser
  data/channels/8838150d-a13b-48d5-83d4-bca30c3b697b.ser
  data/channels/8eb7977e-3223-44ee-910f-df4391a46901.ser
  data/channels/c3e264c2-5287-45cb-8294-59c22352bde8.ser
  data/channels/db1f992f-b6fd-4889-a3f3-0603d0242436.ser
  data/channels/df26883c-41ca-4ef0-abb4-3639a802c7d2.ser
  data/channels/f2586f13-4fbc-4aa5-95d4-d26654ab46d5.ser
  data/channels/fad0ce02-07de-499f-b955-a4afab6daed0.ser
  data/messages/7703b41a-5bc8-498d-8c1f-a23fa375f067.ser
  data/messages/7e27e7ab-6d37-4110-88e1-81f4d5a0727b.ser
  data/users/2b48fbbb-2715-444b-ab8f-b37ea1c4a4f1.ser
  data/users/7b90fd76-c195-4609-8395-d0260ff67a51.ser
  data/users/a0273a66-f9f6-40ab-bd22-cfc361b80ffe.ser
  data/users/b66462c3-7bc8-4765-bf67-4d3fa3e98a7c.ser
  data/users/e781eb50-692e-41ca-83f8-2e709067076e.ser
  data/users/eccb752d-aff7-4cfe-81b0-78facd7143a7.ser
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/ServiceFactory.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/File/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/File/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/File/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#42 [김현기] sprint2
  .idea/3-sprint-mission.iml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  sprint-mission/.gitignore
  sprint-mission/files/channel.ser
  sprint-mission/files/message.ser
  sprint-mission/files/user.ser
  sprint-mission/src/main/java/com/sprint/mission/JavaApplication.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/Message.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/entity/User.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/UserService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  sprint-mission/src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  sprint-mission/src/main/java/com/sprint/mission/testAp.java
  sprint-mission/src/test/repository/Channels.java
  sprint-mission/src/test/repository/Messages.java
  sprint-mission/src/test/repository/Users.java
Labels: 순한맛🐑

#37 [박인규] sprint1
  .gitignore
  .gradle/8.10/checksums/checksums.lock
  .gradle/8.10/checksums/md5-checksums.bin
  .gradle/8.10/checksums/sha1-checksums.bin
  .gradle/8.10/dependencies-accessors/gc.properties
  .gradle/8.10/executionHistory/executionHistory.bin
  .gradle/8.10/executionHistory/executionHistory.lock
  .gradle/8.10/fileChanges/last-build.bin
  .gradle/8.10/fileHashes/fileHashes.bin
  .gradle/8.10/fileHashes/fileHashes.lock
  .gradle/8.10/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_rebase.xml
  .idea/shelf/Uncommitted_changes_before_rebase/buildOutputCleanup.lock
  .idea/shelf/Uncommitted_changes_before_rebase/executionHistory.lock
  .idea/shelf/Uncommitted_changes_before_rebase/shelved.patch
  .idea/vcs.xml
  .idea/workspace.xml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  src/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/JavaApplication.java
  src/main/java/com/sprint/mission/Main.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/control/ChannelControl.java
  src/main/java/com/sprint/mission/discodeit/control/MessageControl.java
  src/main/java/com/sprint/mission/discodeit/control/UserControl.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#61 [조백선] sprint2
  data/channels/8951fd47-a117-48a4-abb8-12da454765a8.ser
  data/users/3d6b9d56-d35f-4f45-9fc1-3d8fdd0a1906.ser
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/entity/BaseEntity.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/menu/ChannelMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/MessageMenu.java
  src/main/java/com/sprint/mission/discodeit/menu/UserMenu.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/integration/ChannelIntegration.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/integration/MessageIntegration.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/integration/UserIntegration.java
Labels: 매운맛🔥

#48 [안여경] sprint2
  README.md
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplicationSprint2.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 매운맛🔥

#55 [이건민] sprint2
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication_File.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/Help
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/data/Message.txt
  src/main/java/com/sprint/mission/discodeit/repository/data/User.txt
  src/main/java/com/sprint/mission/discodeit/repository/data/channel.txt
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicHelp
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/data/channel.txt
  src/main/java/com/sprint/mission/discodeit/service/data/message.txt
  src/main/java/com/sprint/mission/discodeit/service/data/users.txt
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMakeHelp
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
Labels: 순한맛🐑

#62 임정현 sprint2
  src/main/java/com/sprint/mission/discodeit/JavaApplication.java
  src/main/java/com/sprint/mission/discodeit/JavaApplication2.java
  src/main/java/com/sprint/mission/discodeit/entity/Base.java
  src/main/java/com/sprint/mission/discodeit/entity/Channel.java
  src/main/java/com/sprint/mission/discodeit/entity/Message.java
  src/main/java/com/sprint/mission/discodeit/entity/User.java
  src/main/java/com/sprint/mission/discodeit/repository/ChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/MessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/UserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/file/FileUserRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFChannelRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFMessageRepository.java
  src/main/java/com/sprint/mission/discodeit/repository/jcf/JCFUserRepository.java
  src/main/java/com/sprint/mission/discodeit/service/ChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/MessageService.java
  src/main/java/com/sprint/mission/discodeit/service/UserService.java
  src/main/java/com/sprint/mission/discodeit/service/basic/BasicUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/file/FileUserService.java
  src/main/java/com/sprint/mission/discodeit/service/file/data/channel.txt
  src/main/java/com/sprint/mission/discodeit/service/file/data/message.txt
  src/main/java/com/sprint/mission/discodeit/service/file/data/user.txt
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFChannelService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFMessageService.java
  src/main/java/com/sprint/mission/discodeit/service/jcf/JCFUserService.java
  src/test/java/com/sprint/mission/discodeit/repository/ChannelRepositoryTest.java
Labels: 매운맛🔥, 미완성🛠️
